name: Bug Issue
title: '[BUG] '
description: Report a bug with the game.
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: Describe the bug
