name: Feature Issue
title: '[FEATURE] '
description: Request a feature, or a change to a current feature.
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: Describe the feature
