name: Sourcery
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: sourcery-ai/action@v1
        with:
          check: false
